"""loa -> level_of_analysis. less strict LOA column.

Revision ID: 43d2fd1f5ce3
Revises: 1082b4637633
Create Date: 2021-11-22 11:28:26.493766

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '43d2fd1f5ce3'
down_revision = '1082b4637633'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('level_of_analysis',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.add_column('queryset', sa.Column('level_of_analysis', sa.String(), nullable=True))
    op.create_foreign_key(None, 'queryset', 'level_of_analysis', ['level_of_analysis'], ['name'])
    op.drop_column('queryset', 'loa')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queryset', sa.Column('loa', postgresql.ENUM('priogrid_month', 'country_month', name='remoteloas'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'queryset', type_='foreignkey')
    op.drop_column('queryset', 'level_of_analysis')
    op.drop_table('level_of_analysis')
    # ### end Alembic commands ###
