"""Change level_of_analysis FK column name

Revision ID: a1b82a658a9c
Revises: 43d2fd1f5ce3
Create Date: 2021-11-22 14:20:53.246512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b82a658a9c'
down_revision = '43d2fd1f5ce3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queryset', sa.Column('level_of_analysis_id', sa.String(), nullable=True))
    op.drop_constraint('queryset_level_of_analysis_fkey', 'queryset', type_='foreignkey')
    op.create_foreign_key(None, 'queryset', 'level_of_analysis', ['level_of_analysis_id'], ['name'])
    op.drop_column('queryset', 'level_of_analysis')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queryset', sa.Column('level_of_analysis', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'queryset', type_='foreignkey')
    op.create_foreign_key('queryset_level_of_analysis_fkey', 'queryset', 'level_of_analysis', ['level_of_analysis'], ['name'])
    op.drop_column('queryset', 'level_of_analysis_id')
    # ### end Alembic commands ###
