"""Added optional description fields to Queryset and Theme

Revision ID: c74c8402e700
Revises: cf0078099ebf
Create Date: 2021-05-28 13:32:12.179018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c74c8402e700'
down_revision = 'cf0078099ebf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queryset', sa.Column('description', sa.String(), nullable=True))
    op.add_column('theme', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('theme', 'description')
    op.drop_column('queryset', 'description')
    # ### end Alembic commands ###
