"""From models

Revision ID: cf0078099ebf
Revises: d21a5eb2a764
Create Date: 2021-05-20 13:07:22.854059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf0078099ebf'
down_revision = 'd21a5eb2a764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queryset',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('loa', sa.Enum('priogrid_month', 'country_month', name='remoteloas'), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('theme',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('op',
    sa.Column('base_path', sa.Enum('trf', 'base', name='remotebases'), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('args', sa.JSON(), nullable=True),
    sa.Column('queryset_name', sa.String(), nullable=True),
    sa.Column('op_id', sa.Integer(), nullable=False),
    sa.Column('next_op_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['next_op_id'], ['op.op_id'], ),
    sa.ForeignKeyConstraint(['queryset_name'], ['queryset.name'], ),
    sa.PrimaryKeyConstraint('op_id')
    )
    op.create_table('querysets_themes',
    sa.Column('theme_name', sa.String(), nullable=True),
    sa.Column('queryset_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['queryset_name'], ['queryset.name'], ),
    sa.ForeignKeyConstraint(['theme_name'], ['theme.name'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('querysets_themes')
    op.drop_table('op')
    op.drop_table('theme')
    op.drop_table('queryset')
    # ### end Alembic commands ###
